name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Find vcomp140.dll and set environment variable
      run: |
        python -c "import sklearn, os; dll_path = os.path.join(os.path.dirname(sklearn.__file__), '.libs', 'vcomp140.dll'); print(f'vcomp140.dll path: {dll_path}'); with open(os.environ['GITHUB_ENV'], 'a') as f: f.write(f'VCOMP140_DLL_PATH={dll_path}\n')"

    - name: Build executable with PyInstaller
      working-directory: bapat
      run: |
        echo %VCOMP140_DLL_PATH%
        pyinstaller app.py --name PerformanceApp --onedir --windowed --icon=app.ico --clean --specpath . --collect-all sklearn --add-binary "%VCOMP140_DLL_PATH%;sklearn\\.libs"

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: PerformanceApp-Windows
        path: bapat/dist/
