name: Build MacOS Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Universal Binary with PyInstaller
      working-directory: bapat
      run: |
        pyinstaller app.py \
          --name PerformanceApp \
          --onedir \
          --windowed \
          --icon=app.icns \
          --clean \
          --specpath . \
          --target-arch universal2

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: PerformanceApp-macOS
        path: bapat/dist/