name: Build MacOS Executable (arm64)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-arm64:
    runs-on: macos-14 #macos-latest  # Specify macOS arm64 runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      # Use system Python which is arm64
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Build arm64 Binary with PyInstaller
      working-directory: bapat
      run: |
        source ../venv/bin/activate
        pyinstaller app.py \
          --name PerformanceApp \
          --onedir \
          --windowed \
          --icon=app.icns \
          --clean \
          --specpath . \
          --target-arch arm64

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: PerformanceApp-macOS-arm64
        path: bapat/dist/
